apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: ghcr.io/yandex-practicum/scaletestapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              # Для локального тестирования HPA в Minikube/WSL.
              # Лимит памяти приложения оставлен 30Mi, как требуется в задании,
              # но memory request намеренно задан как 1Mi, чтобы HPA мог
              # показать масштабирование по утилизации памяти без чрезмерной нагрузки на локальный компьютер.
              # В production memory requests должны подбираться на основе реального профилирования приложения.
              memory: 1Mi
              cpu: 100m
            limits:
              memory: 30Mi
              cpu: 500m
